### ISSUE TITLE
build: gulp build raises error 'ReferenceError: primordials is not defined'

### ISSUE THREAD

**Issue by vdias38** [meumobi/ng-meumobi-utils#14]
```sh
% gulp -v
[11:56:14] CLI version 3.9.1
[11:56:14] Local version 3.9.1
% npm -v
6.14.16
% gulp build
fs.js:36
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:36:5
    at req_ (/Users/vdias38/Dvpt/PROJECTS/ng-meumobi-utils/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/vdias38/Dvpt/PROJECTS/ng-meumobi-utils/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/vdias38/Dvpt/PROJECTS/ng-meumobi-utils/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
%
```

**Comment by vdias38** [comment]
> issue occurs if working w/ gulp@3.9.1 on Node.js 12+.
> fix enable you to use Node.js 12+ with gulp@3.9.1 by overriding graceful-fs to version ^4.2.10.

https://stackoverflow.com/a/58394828/4982169
